#!/usr/bin/env python3
"""render-world-map.py — offline world-map generator for R2H RSC (runescapeclassic.gold).

Generates static map images for each floor from OUR OWN game cache archives
(public/game/cache/maps63.jag/.mem + land63.jag/.mem). Nothing is fetched from
any external site; the terrain palette and overlay colours are generated by the
same algorithms the client uses (mirrored from the open rsc-landscape spec and
our own WorldLoader.java parse logic).

Reads COPIES of the archives from a scratch dir; writes PNGs + map-meta.json
to the frontend public/assets/map/ directory.

Usage:
  python3 render-world-map.py <cache_dir> <out_dir> [--scale N] [--labels areas.json]

Coordinate system (matches server Point / areas.json):
  - world tile x: 0..1007 (practical 0..~944), increases WEST
  - world tile y (raw): 0..4031; floor = y // 944; localY = y % 944, increases SOUTH
  - sector (h, XX, YY): tiles x in [XX*48, (XX+1)*48), localY in [YY*48, (YY+1)*48)
  - IMAGE IS MIRRORED ON X so the map reads north-up with east on the right,
    matching every published RSC world map (Varrock east, Falador west).
"""
import bz2
import json
import math
import os
import struct
import sys

SECTOR = 48
FLOOR_STRIDE = 944

# ---------------------------------------------------------------- JAG archive
def jag_hash(name: str) -> int:
    h = 0
    for c in name.upper():
        h = (h * 61 + (ord(c) - 32)) & 0xFFFFFFFF
    return h


def jag_members(path: str):
    """Returns {name_hash: bytes} for a .jag archive (header-stripped bzip2)."""
    data = open(path, "rb").read()
    usize = int.from_bytes(data[0:3], "big")
    csize = int.from_bytes(data[3:6], "big")
    body = data[6 : 6 + csize]
    if usize != csize:
        body = bz2.decompress(b"BZh9" + body)
    n = struct.unpack(">H", body[0:2])[0]
    out = {}
    off = 2
    table = []
    for _ in range(n):
        h = struct.unpack(">I", body[off : off + 4])[0]
        us = int.from_bytes(body[off + 4 : off + 7], "big")
        cs = int.from_bytes(body[off + 7 : off + 10], "big")
        table.append((h, us, cs))
        off += 10
    for h, us, cs in table:
        raw = body[off : off + cs]
        off += cs
        if us != cs:
            raw = bz2.decompress(b"BZh9" + raw)
        out[h] = raw
    return out


# ------------------------------------------------------- sector file parsing
def rle(buf, size=SECTOR * SECTOR, fill_last=False):
    """WorldLoader RLE: <128 → literal (repeat semantics per caller), >=128 → run."""
    out = bytearray(size)
    i = 0
    last = 0
    p = 0
    while i < size:
        val = buf[p]
        p += 1
        if val < 128:
            out[i] = val
            i += 1
            last = val
        else:
            run = val - 128
            for _ in range(run):
                if i < size:
                    out[i] = last
                    i += 1
    return bytes(out), p


def parse_hei(raw: bytes):
    """land archive .hei → terrainHeight[2304], terrainColour[2304] (tile index = x*48+y)."""
    # block 1: height, literal sets value (no lastVal reuse in WorldLoader .hei path)
    size = SECTOR * SECTOR
    height = bytearray(size)
    colour = bytearray(size)
    i = 0
    last = 0
    p = 0
    while i < size:
        val = raw[p]
        p += 1
        if val < 128:
            height[i] = val
            i += 1
            last = val
        else:
            for _ in range(val - 128):
                if i < size:
                    height[i] = last
                    i += 1
    # block 2: colour with lastVal reuse
    last = 0
    while i < size * 2 and p < len(raw):
        val = raw[p]
        p += 1
        if val < 128:
            colour[i - size] = val
            i += 1
            last = val
        else:
            for _ in range(val - 128):
                if i - size < size:
                    colour[i - size] = last
                    i += 1
    # WorldLoader post-processing on height (delta + &0x7f, *2)
    lastv = 64
    for ty in range(SECTOR):
        for tx in range(SECTOR):
            idx = tx * SECTOR + ty
            lastv = (height[idx] + lastv) & 0x7F
            height[idx] = (lastv * 2) & 0xFF
    return height, colour


def parse_dat(raw: bytes, alt_format: bool = False):
    """maps archive .dat (standard format, based_map_data=64) → per-tile overlay + walls.

    WorldLoader standard path (WorldLoader.java:162-207): walls EW, NS, diagonal
    are RAW 2304 bytes each; roof RLE zero-fill; tileDecoration RLE lastVal-fill;
    tileDirection RLE zero-fill. (The alt/14-era format RLEs the wall blocks too.)
    """
    size = SECTOR * SECTOR
    p = 0

    walls_ew = bytearray(raw[p:p + size]); p += size
    walls_ns = bytearray(raw[p:p + size]); p += size
    walls_diag = bytearray(raw[p:p + size]); p += size
    # 4th raw block: diagonal-wall overlay (val>0 → +12000 diagonal object)
    p += size

    def read_rle(fill_last_val: bool):
        nonlocal p
        out = bytearray(size)
        i = 0
        last = 0
        while i < size:
            val = raw[p]
            p += 1
            if val < 128:
                out[i] = val
                i += 1
                if fill_last_val:
                    last = val
            else:
                run = val - 128
                for _ in range(run):
                    if i < size:
                        out[i] = last if fill_last_val else 0
                        i += 1
        return out

    walls_roof = read_rle(False)
    deco = read_rle(True)     # tileDecoration keeps lastVal
    direction = read_rle(False)
    return walls_ew, walls_ns, walls_diag, walls_roof, deco, direction


# --------------------------------------------------- client terrain palette
def build_terrain_palette():
    """256-entry palette, same generation as the client (rsc-landscape terrain-colours)."""
    rgb = []
    for i in range(64):  # 0-63: white-grey ramp
        r = 255 - i * 4
        g = 255 - int(i * 1.75)
        b = 255 - i * 4
        rgb.append((r, g, b))
    for i in range(64):  # 64-127: green ramp
        rgb.append((i * 3, 144, 0))
    for i in range(64):  # 128-191: yellow-brown ramp
        rgb.append((192 - int(i * 1.5), 144 - int(i * 1.5), 0))
    for i in range(64):  # 192-255: brown-dark ramp
        rgb.append((96 - int(i * 1.5), 48 + int(i * 1.5), 0))
    # map colours = client colour with HALF the lightness (hsv v / 2), like the world map
    out = []
    for (r, g, b) in rgb:
        h, s, v = rgb_to_hsv(r, g, b)
        v = v / 2.0
        out.append(hsv_to_rgb(h, s, v))
    return out


def rgb_to_hsv(r, g, b):
    r, g, b = r / 255.0, g / 255.0, b / 255.0
    mx, mn = max(r, g, b), min(r, g, b)
    v = mx
    s = 0 if mx == 0 else (mx - mn) / mx
    if mx == mn:
        h = 0
    elif mx == r:
        h = (60 * ((g - b) / (mx - mn))) % 360
    elif mx == g:
        h = 60 * ((b - r) / (mx - mn)) + 120
    else:
        h = 60 * ((r - g) / (mx - mn)) + 240
    return h, s, v


def hsv_to_rgb(h, s, v):
    c = v * s
    x = c * (1 - abs(((h / 60.0) % 2) - 1))
    m = v - c
    hh = int(h // 60) % 6
    rgb = [(c, 0, 0), (c, x, 0), (0, c, 0), (0, c, x), (0, 0, c), (x, 0, c)][hh]
    return (
        int(round((rgb[0] + m) * 255)),
        int(round((rgb[1] + m) * 255)),
        int(round((rgb[2] + m) * 255)),
    )


# overlay id → map colour (rsc-landscape tile-overlays; water/road/lava/mountain)
OVERLAY_COLOURS = {
    1: (64, 64, 64),      # road
    2: (36, 64, 127),     # water
    3: (100, 48, 2),      # brown floor
    4: (100, 48, 2),      # bridge
    5: (64, 64, 64),      # stone floor
    6: (107, 3, 15),      # maroon floor
    7: (34, 48, 58),      # swamp water
    8: (45, 45, 52),      # hole (darkened so it doesn't read as map void)
    9: (97, 97, 97),      # mountain
    10: (255, 0, 255),    # black (magenta marker in ref maps)
    11: (96, 48, 1),      # lava
    12: (100, 48, 2),     # bridge 2
    13: (31, 63, 125),    # blue floor
    14: (64, 64, 64),     # pentagram
    15: (36, 22, 9),      # purple floor
    16: (45, 45, 52),     # black floor (darkened, not pure black)
    17: (121, 123, 120),  # light stone floor
    18: (45, 45, 52),     # object platform
    19: (45, 45, 52),     # black_2
    20: (45, 45, 52),     # object_platform_2
    21: (100, 48, 2),     # log bridge
}


def load_floor_data(cache_dir):
    """Load all four archives; return per-floor dict {(sectorXX, sectorYY): {hei, dat}}."""
    land_jag = jag_members(os.path.join(cache_dir, "land63.jag"))
    land_mem = jag_members(os.path.join(cache_dir, "land63.mem"))
    map_jag = jag_members(os.path.join(cache_dir, "maps63.jag"))
    map_mem = jag_members(os.path.join(cache_dir, "maps63.mem"))

    sectors = {}  # (h, XX, YY) -> dict
    for h in range(4):
        for xx in range(100):
            for yy in range(100):
                base = f"m{h}{xx:02d}{yy:02d}"
                hei = None
                dat = None
                # .hei from land archives (members overrides f2p)
                hj = land_jag.get(jag_hash(base + ".hei"))
                hm = land_mem.get(jag_hash(base + ".hei"))
                hei = hm if hm is not None else hj
                # .dat from maps archives
                dj = map_jag.get(jag_hash(base + ".dat"))
                dm = map_mem.get(jag_hash(base + ".dat"))
                dat = dm if dm is not None else dj
                if hei is None and dat is None:
                    continue
                sectors[(h, xx, yy)] = {"hei": hei, "dat": dat}
    return sectors


def render_floor(floor, sectors, palette, areas, scale=2, out_dir=".", font_path=None):
    from PIL import Image, ImageDraw, ImageFont

    # canvas covering the practical world: x 0..944, localY 0..944 (1px per tile * scale)
    W = 944 * scale
    H = 944 * scale
    img = Image.new("RGB", (W, H), (17, 17, 17))
    px = img.load()
    covered = set()

    for (h, xx, yy), data in sectors.items():
        if h != floor:
            continue
        height = colour = None
        if data["hei"] is not None:
            height, colour = parse_hei(data["hei"])
        ew, ns, diag, roof, deco, direction = (None,) * 6
        if data["dat"] is not None:
            ew, ns, diag, roof, deco, direction = parse_dat(data["dat"])

        for tx in range(SECTOR):
            for ty in range(SECTOR):
                idx = tx * SECTOR + ty
                # WorldLoader sector→world mapping: wildX=2304, wildY=1776
                # (WorldLoader.java:525-531); sector XX 48..69, YY 37..56.
                wx = xx * SECTOR - 2304 + tx   # world x
                wy = yy * SECTOR - 1776 + ty   # floor-local y
                if wx < 0 or wx >= 944 or wy < 0 or wy >= 944:
                    continue
                c = None
                if deco is not None:
                    ov = deco[idx]
                    if ov in OVERLAY_COLOURS:
                        c = OVERLAY_COLOURS[ov]
                if c is None and colour is not None:
                    base = palette[colour[idx]]
                    if height is not None:
                        # subtle elevation shading like the client's lit terrain
                        hh = height[idx]
                        f = 0.85 + (hh / 255.0) * 0.3
                        c = (
                            max(0, min(255, int(base[0] * f))),
                            max(0, min(255, int(base[1] * f))),
                            max(0, min(255, int(base[2] * f))),
                        )
                    else:
                        c = base
                if c is None:
                    c = (17, 17, 17)
                # MIRROR X: image column = (944 - 1 - wx) so the map reads east-right
                for sx in range(scale):
                    for sy in range(scale):
                        px[(944 - 1 - wx) * scale + sx, wy * scale + sy] = c
                covered.add((wx, wy))
    print(f"  floor {floor}: {len(covered)} tiles covered")

    # ---- labels from areas.json ----
    d = ImageDraw.Draw(img)
    labels = []
    for a in areas:
        if not a.get("label", False) or floor not in a.get("floors", []):
            continue
        if a.get("type") in ("bank",):
            size = 13
        elif a.get("type") in ("town", "dungeon"):
            size = 17
        else:
            size = 15
        labels.append((a, size))

    font_cache = {}

    def get_font(size):
        if size not in font_cache:
            if font_path and os.path.exists(font_path):
                font_cache[size] = ImageFont.truetype(font_path, size)
            else:
                font_cache[size] = ImageFont.load_default()
        return font_cache[size]

    def world_to_px(x, local_y):
        # MIRRORED X transform (same as tiles above)
        return ((944 - 1 - x) * scale, local_y * scale)

    for a, size in labels:
        cx = (a["x1"] + a["x2"]) / 2
        cy = (a["y1"] + a["y2"]) / 2
        px_x, px_y = world_to_px(cx, cy)
        label = a["name"]
        font = get_font(size)
        bbox = d.textbbox((0, 0), label, font=font)
        tw = bbox[2] - bbox[0]
        th = bbox[3] - bbox[1]
        # shadow + text
        d.text((px_x - tw / 2 + 1, px_y - th / 2 + 1), label, font=font, fill=(0, 0, 0))
        colour = (255, 255, 0) if a.get("type") == "town" else (255, 255, 255)
        if a.get("type") == "kingdom":
            colour = (200, 200, 200)
        d.text((px_x - tw / 2, px_y - th / 2), label, font=font, fill=colour)

    out = os.path.join(out_dir, f"map-f{floor}.png")
    img.save(out, "PNG", optimize=True)
    print(f"  wrote {out} ({img.size[0]}x{img.size[1]})")
    return covered


def main():
    cache_dir = sys.argv[1]
    out_dir = sys.argv[2]
    scale = 2
    labels_path = None
    args = sys.argv[3:]
    if "--scale" in args:
        scale = int(args[args.index("--scale") + 1])
    if "--labels" in args:
        labels_path = args[args.index("--labels") + 1]
    if "--font" in args:
        font_arg = args[args.index("--font") + 1]
    else:
        font_arg = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

    areas = []
    if labels_path:
        areas = json.load(open(labels_path)).get("areas", [])
    os.makedirs(out_dir, exist_ok=True)

    print("Loading archives…")
    sectors = load_floor_data(cache_dir)
    print(f"  {len(sectors)} sectors loaded")
    palette = build_terrain_palette()

    meta = {"scale": scale, "size": [944 * scale, 944 * scale], "floors": {}, "mirrorX": True}
    for floor in range(4):
        covered = render_floor(floor, sectors, palette, areas, scale, out_dir, font_arg)
        meta["floors"][str(floor)] = {"tiles": len(covered)}

    with open(os.path.join(out_dir, "map-meta.json"), "w") as f:
        json.dump(meta, f, indent=2)
    print("wrote map-meta.json")


if __name__ == "__main__":
    main()
